stages:
    - test

Test:
  image: python:2
  before_script:
      - pip install -r requirements_dev.txt
      - mkdir -p /etc/agora
      - cd ./agora
      - cp ./docker/settings_ci.conf /etc/agora/settings.conf
      - cp ./docker/deployment.conf /etc/agora/deployment.conf
      - python manage.py migrate
  script:
      - pytest
