sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "6"
env:
    - EMBER_VERSION=2.9.0-beta.1
install:
    - yarn
script:
    - ember build
