---

- mysql_user:
    login_user: "root"
    login_password: ""
    name: root
    password: anex
    priv: '*.*:ALL'
    state: present

- copy:
    src: "../files/.my.cnf"
    dest: "/root/"
    owner: root
    group: root
    mode: 0600
