---

- hosts: agora-ansible
  roles:
    - common
    - agora
  handlers:
    - name: restart apache
      service: name=apache2 state=restarted

- hosts: 127.0.0.1
  roles:
    - local

- hosts: agora-ansible
  roles:
    - deploy
    - django
    - django_admin
  handlers:
    - name: restart apache
      service: name=apache2 state=restarted
